//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бухгалтерия
    {
        public int ID { get; set; }
        public System.DateTime Дата { get; set; }
        public string НазваниеОрг { get; set; }
        public string АдресОрг { get; set; }
        public string Коммерческая { get; set; }
        public string ВидЗатрат { get; set; }
        public decimal Сумма { get; set; }
    }
}
